In [4]:
#creating a numpy array
#creating a numpy array from a list
import numpy as np
array1=np.array([1,2,3,4,5,6])
print(array1)
print(type(array1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [6]:
#creating a numpy array from a tuple
array2=np.array((1,2,3,4,5,6))
print(array2)
print(array2.dtype)#print the type of the value inside the numpy array.

[1 2 3 4 5 6]
int32


In [8]:
#creating a 2-D array from lists
array3=np.array([[1,2,3],[4,3,5],[4,8,4]])
print(array3)

[[1 2 3]
 [4 3 5]
 [4 8 4]]


In [9]:
#to change the datatype 
array4=np.array([1,2,3,4,5],dtype=float)
print(array4.dtype)

float64


In [10]:
#appending new elements to an numpy array
array5=np.array([1,2,3,4,5])
print(np.append(array5,[11,12,13]))#append the list to the end of array5
print(array5)#The original array is not changed.
arr6=np.append(array5,[11,12,13])
print(arr6)

[ 1  2  3  4  5 11 12 13]
[1 2 3 4 5]
[ 1  2  3  4  5 11 12 13]


In [20]:
array7=np.array([[1,2,3],[4,5,6]])
print(array7)
arr8=np.append(array7,[1,2,3])
print(arr8)#we can see that since we have not specified the axis it will first flatten the array and then append elements to it


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 1 2 3]


In [24]:
array7=np.array([[1,2,3],[4,5,6]])
print(array7)
arr8=np.array([[21,22,23],[13,14,15]])
arr9=np.append(array7,arr8,axis=1)#axis=1 append column wise
print(arr9)
arr10=np.append(array7,arr8,axis=0)#append row wise
print(arr10)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3 21 22 23]
 [ 4  5  6 13 14 15]]
[[ 1  2  3]
 [ 4  5  6]
 [21 22 23]
 [13 14 15]]


In [26]:
#sorting numpy arrays 
arr1=np.array([19,12,1,2,33,4,5,56,11])
res=np.sort(arr1)#sorting our numpy array
res2=np.sort(arr1)[::-1]
print(res)#sorted array
print(res2)#sorted array in descending order

[ 1  2  4  5 11 12 19 33 56]
[56 33 19 12 11  5  4  2  1]


In [29]:
#using different types of sorting algorithms
res3=np.sort(arr1,kind='quicksort')
print(res3)
res4=np.sort(arr1,kind='mergesort')
print(res4)
res5=np.sort(arr1,kind='stable')
print(res5)
res6=np.sort(arr1,kind='heapsort')
print(res6)

[ 1  2  4  5 11 12 19 33 56]
[ 1  2  4  5 11 12 19 33 56]
[ 1  2  4  5 11 12 19 33 56]
[ 1  2  4  5 11 12 19 33 56]


In [42]:
#sorting a 2-D array
arr2d=np.array([[11,2,3],[5,6,17],[18,19,10]])
print(arr2d)
arr2d.sort(axis=0)#sorting array according to columns.
print(arr2d)

[[11  2  3]
 [ 5  6 17]
 [18 19 10]]
[[ 5  2  3]
 [11  6 10]
 [18 19 17]]
[[ 2  3  5]
 [ 6 10 11]
 [17 18 19]]


In [43]:
arr2d=np.array([[11,2,3],[5,6,17],[18,19,10]])
arr2d.sort(axis=1)
print(arr2d)

[[ 2  3 11]
 [ 5  6 17]
 [10 18 19]]


In [48]:
#saving a numpy array to a .csv file
arry1=np.array([[1,2,3],[4,5,6]])
np.savetxt('samplenp.txt',arry1)
np.savetxt('samplenp.csv',arry1,delimiter=',')
np.savetxt('samplenp_new.csv',arry1,delimiter=',',fmt='%d')

In [50]:
#reversing a numpy array
arr1=np.array([1,2,3,4,5,6])
arr2=np.flip(arr1)
print(arr2)

[1 2 3 4 5 6]


In [61]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.flip(arr2,axis=1)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [62]:
np.flip(arr2,axis=0)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])