In [4]:
#creating a numpy array
#creating a numpy array from a list
import numpy as np
array1=np.array([1,2,3,4,5,6])
print(array1)
print(type(array1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [6]:
#creating a numpy array from a tuple
array2=np.array((1,2,3,4,5,6))
print(array2)
print(array2.dtype)#print the type of the value inside the numpy array.

[1 2 3 4 5 6]
int32


In [8]:
#creating a 2-D array from lists
array3=np.array([[1,2,3],[4,3,5],[4,8,4]])
print(array3)

[[1 2 3]
 [4 3 5]
 [4 8 4]]


In [9]:
#to change the datatype 
array4=np.array([1,2,3,4,5],dtype=float)
print(array4.dtype)

float64


In [10]:
#appending new elements to an numpy array
array5=np.array([1,2,3,4,5])
print(np.append(array5,[11,12,13]))#append the list to the end of array5
print(array5)#The original array is not changed.
arr6=np.append(array5,[11,12,13])
print(arr6)

[ 1  2  3  4  5 11 12 13]
[1 2 3 4 5]
[ 1  2  3  4  5 11 12 13]


In [20]:
array7=np.array([[1,2,3],[4,5,6]])
print(array7)
arr8=np.append(array7,[1,2,3])
print(arr8)#we can see that since we have not specified the axis it will first flatten the array and then append elements to it


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6 1 2 3]


In [24]:
array7=np.array([[1,2,3],[4,5,6]])
print(array7)
arr8=np.array([[21,22,23],[13,14,15]])
arr9=np.append(array7,arr8,axis=1)#axis=1 append column wise
print(arr9)
arr10=np.append(array7,arr8,axis=0)#append row wise
print(arr10)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3 21 22 23]
 [ 4  5  6 13 14 15]]
[[ 1  2  3]
 [ 4  5  6]
 [21 22 23]
 [13 14 15]]


In [26]:
#sorting numpy arrays 
arr1=np.array([19,12,1,2,33,4,5,56,11])
res=np.sort(arr1)#sorting our numpy array
res2=np.sort(arr1)[::-1]#this worked as we have not specified a starting or ending index so it selected the entire array and the 
#stepsize is -1 hence is selected the elements from the last element.
print(res)#sorted array
print(res2)#sorted array in descending order

[ 1  2  4  5 11 12 19 33 56]
[56 33 19 12 11  5  4  2  1]


In [29]:
#using different types of sorting algorithms
res3=np.sort(arr1,kind='quicksort')
print(res3)
res4=np.sort(arr1,kind='mergesort')
print(res4)
res5=np.sort(arr1,kind='stable')
print(res5)
res6=np.sort(arr1,kind='heapsort')
print(res6)

[ 1  2  4  5 11 12 19 33 56]
[ 1  2  4  5 11 12 19 33 56]
[ 1  2  4  5 11 12 19 33 56]
[ 1  2  4  5 11 12 19 33 56]


In [42]:
#sorting a 2-D array
arr2d=np.array([[11,2,3],[5,6,17],[18,19,10]])
print(arr2d)
arr2d.sort(axis=0)#sorting array according to columns.
print(arr2d)

[[11  2  3]
 [ 5  6 17]
 [18 19 10]]
[[ 5  2  3]
 [11  6 10]
 [18 19 17]]
[[ 2  3  5]
 [ 6 10 11]
 [17 18 19]]


In [43]:
arr2d=np.array([[11,2,3],[5,6,17],[18,19,10]])
arr2d.sort(axis=1)
print(arr2d)

[[ 2  3 11]
 [ 5  6 17]
 [10 18 19]]


In [48]:
#saving a numpy array to a .csv file
arry1=np.array([[1,2,3],[4,5,6]])
np.savetxt('samplenp.txt',arry1)
np.savetxt('samplenp.csv',arry1,delimiter=',')
np.savetxt('samplenp_new.csv',arry1,delimiter=',',fmt='%d')

In [50]:
#reversing a numpy array
arr1=np.array([1,2,3,4,5,6])
arr2=np.flip(arr1)
print(arr2)

[1 2 3 4 5 6]


In [61]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.flip(arr2,axis=1)

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [62]:
np.flip(arr2,axis=0)

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [4]:
import numpy as np
#we can also create a numpy array using np.arage(start,stop,step)
arr1=np.arange(1,20,2)
print(arr1)

[ 1  3  5  7  9 11 13 15 17 19]


In [7]:
#selecting elements from the numpy array based on conditions
boolarr=arr1<10
print(boolarr)#now we can index our numpy array
new_arr1=arr1[boolarr]
print(new_arr1)

#we can also do all of this in a single line as 
print(arr1[arr1<10])

[ True  True  True  True  True False False False False False]
[1 3 5 7 9]
[1 3 5 7 9]


In [14]:
#we can also select elements using more complex conditions
print(arr1[(arr1>5) & (arr1<16)])

[ 7  9 11 13 15]


In [25]:
#selecting elements in a numpy array
arr1=np.array([[1,2,3],[4,5,6],[11,12,13]])
print(arr1)
#the basic syntax of selecting elements from the numpy array is np[row index][column index]
print(arr1[2][1])
#we can also do this
print(arr1[2,1])
#we can also do multiple selection as follows
print(arr1[:2,:])#first 2 rows and all the columns 
print(arr1[:,:2])#print all the rows and first two columns

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]]
12
12
[[1 2 3]
 [4 5 6]]
[[ 1  2]
 [ 4  5]
 [11 12]]


In [30]:
row=arr1[1]
print(row)
row[:]=123
print(row)
print(arr1)#changes done in the subset were reflected in the original array as well!

[123 123 123]
[123 123 123]
[[  1   2   3]
 [123 123 123]
 [ 11  12  13]]


In [32]:
#if we dont want this to happen what we need to do is use the copy()
row2=arr1[1].copy()
print(row2)
row2[:]=293
print(row2)
print(arr1)#although row2 has changed arr1 is still the same.

[123 123 123]
[293 293 293]
[[  1   2   3]
 [123 123 123]
 [ 11  12  13]]


In [34]:
#creating a subarray of a numpy array
arr1=np.arange(1,20)
print(arr1)
subarr=arr1[:7]
print(subarr)#creating this subarray is just the view of the actual array data is not actually copied any changes done to the 
#subarray will reflect in the actual array.
subarr[1]=22
print(subarr)
print(arr1)
#we can use the copy() here as well 
subarr2=arr1[:7].copy()
subarr2[1:3]=99
print(subarr2)
print(arr1)#arr1 is not changed in this case

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1 2 3 4 5 6 7]
[ 1 22  3  4  5  6  7]
[ 1 22  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1 99 99  4  5  6  7]
[ 1 22  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [66]:
#deleting elements based on certain conditions from a numpy array
arr1=np.arange(1,30)
print(arr1)
print(np.argwhere(arr1>25))#we are getting the index positions where the condition specified is True
print(arr1[28])#index pos 28
#so deleting elements from our numpy array where the value is greater then 25
arr=np.delete(arr1,np.argwhere(arr1>25))
print(arr1)
print(arr)#deleted last 5 values and created a new numpy array
#we can also delete elements based on multiple conditions using this same technique.
arr2=np.delete(arr1,np.argwhere((arr1>5)&(arr1<10)))
print(arr2)
print(arr1)
print(np.delete(arr1,1))#delete element at index pos 1
print(np.delete(arr1,[2,3,4]))#delete elements at these index positions

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]
[[25]
 [26]
 [27]
 [28]]
29
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[ 1  2  3  4  5 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28
 29]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]
[ 1  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29]
[ 1  2  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29]


In [50]:
np.argwhere((arr1>5)&(arr1<10))

array([[5],
       [6],
       [7],
       [8]], dtype=int64)

In [59]:
#np.where() examples
arr1=np.arange(1,30)
print(np.where(arr1>24,1,0))
#we can also do complex condition checking
print(np.where((arr1>25) & (arr1<28)))
arr2=np.array([11,12,13])
print(np.where(arr2>12,[1,2,3],[7,8,9]))#when we are passing all three arguments the length of all the three arrays must be the same.


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1]
(array([25, 26], dtype=int64),)
[7 8 3]


In [62]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.arange(1,20)
#to get the dimensions of both these arrays
dim1=arr1.shape
dim2=arr2.shape
print(dim1,dim2)
print(f'number of rows arr1 {dim1[0]} number of cols {dim1[1]}')

(2, 3) (19,)
number of rows arr1 2 number of cols 3


In [63]:
#we can also work with np.size()
arr1=np.array([[1,2,3],[4,5,6]])
print(np.size(arr1,axis=0))#number of rows
print(np.size(arr1,axis=1))#number of columns
print(np.size(arr1))#the number of elements in the numpy array

2
3
6


In [67]:
#np.linspace() is used to create a number of evenly spaced samples
np.linspace(2,20,5)#start end number of samples

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [69]:
print(np.linspace(2,30,10,dtype=np.int32))#we can also specify the dtype

[ 2  5  8 11 14 17 20 23 26 30]


In [92]:
#finding the minimum value in a numpy array and its index
arr1=np.array([35,22,31,24,3,44,11,1,234,56,7,8,93,])
print(np.amin(arr1))#we can use the np.amin() to find the minimum value inside the numpy array\
print(np.argwhere(arr1==np.amin(arr1)))#index position of the minimum element
#we can also work with higher dimensional arrays
arr2=np.array([[11,12,3],[37,3,33],[51,23,34]])
print(np.amin(arr2,axis=0))#will return the minimum value for each column
print(np.amin(arr2,axis=1))#will return the minimum value for each row
print(np.argwhere(arr2==np.amin(arr2)))#minimum values in the 2-D numpy array.

arr3=np.array([[1,2,3],[np.NAN,32,11]])
print(np.amin(arr3))#if our numpy array contains a NaN then np.amin() will return NaN
print(np.nanmin(arr3))#use np.nanmin() to ignore the NaN and find the min value.
#we can do all these things for max values using np.amax()

1
[[7]]
[11  3  3]
[ 3  3 23]
[[0 2]
 [1 1]]
nan
1.0


In [94]:
#creating numpy arrays of various shapes using np.zeros() np.ones() and np.eye()
print(np.zeros(5))
print(np.zeros((5,6)))
print(np.ones(5))
print(np.ones((5,6)))
print(np.eye(5))

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [95]:
#creating a numpy array of different shapes initialized with the same value
np.full(10,5)#10 elements filled with the value 5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [97]:
np.full((3,5),10)#3*5 matrix 

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [100]:
#checking all the unique values inside the numpy array and returning the indexes of those elements.
arr=np.array([1,2,3,13,14,15,16,11,15,2,3])
unique_vals=np.unique(arr)
print(unique_vals)
unique_vals,index=np.unique(arr,return_index=True)
print(unique_vals)
print(index)

[ 1  2  3 11 13 14 15 16]
[ 1  2  3 11 13 14 15 16]
[0 1 2 7 3 4 5 6]


In [4]:
#structured array
#a structured array is simmilar to the structure in c 
#we need to define a type and then create numpy arrays of that defined type
import numpy as np
custom_type = [('Name', (np.str_, 10)), ('Age', np.float64), ('Date', np.int32)]
custom_arr = np.array([('Alex', 12, 1), ('Nicole', 24,15), ('Mark', 6, 12), ('Andrew', 8, 2)], dtype=custom_type)
print(custom_arr)
print(type(custom_arr))
print(custom_arr.dtype)

[('Alex', 12.,  1) ('Nicole', 24., 15) ('Mark',  6., 12)
 ('Andrew',  8.,  2)]
<class 'numpy.ndarray'>
[('Name', '<U10'), ('Age', '<f8'), ('Date', '<i4')]


In [5]:
#sorting our structured array
mod_array=np.sort(custom_arr,order='Name')#sorting our custom array wrt Name
print(mod_array)

[('Alex', 12.,  1) ('Andrew',  8.,  2) ('Mark',  6., 12)
 ('Nicole', 24., 15)]


In [6]:
mod_array=np.sort(custom_arr,order=['Name','Age'])#sorting our custom array wrt Name and age
print(mod_array)

[('Alex', 12.,  1) ('Andrew',  8.,  2) ('Mark',  6., 12)
 ('Nicole', 24., 15)]


In [3]:
#concatenating numpy arrays together
vals=input().split()


1 2 3 4
['1', '2', '3', '4']


In [1]:
import numpy as np
rolls=np.random.randint(high=6,low=1,size=10)
print(rolls)#die rolls

[3 5 1 5 2 2 3 1 1 5]
